### ISSUE TITLE
Frame-level Features Type

### ISSUE THREAD

**Issue by jvel07** [KrishnaDN/x-vector-pytorch#3]
Hi, nice work!
Got one minor question. In the paper cited, Snyder et. al use MFCC features.
Here, however, it seems like you are using linear spectrograms instead. Is that on purpose?
Are they performing better than MFCCs for the DNN case?

**Comment by KrishnaDN** [comment]
> Hi, nice work!
> Got one minor question. In the paper cited, Snyder et. al use MFCC features.
> Here, however, it seems like you are using linear spectrograms instead. Is that on purpose?
> Are they performing better than MFCCs for the DNN case?

I have implemented both MFCC and STFT features. You can change it to MFCC in utils.py code

**Comment by jvel07** [comment]
Thanks, I did not find the MFCCs part in utils.py tho. However, it's not a problem. 
Since the network expects the same sized tensors, the question would be: 
under what criteria did you equal the sizes of the MFCCs at the moment of inputting them to the DNN?
